### ISSUE TITLE
Android Studio can't connect to Pieces OS

### ISSUE THREAD

**Issue by mdev88** [pieces-app/documentation#34]
OS: Manjaro Linux (up to date)
Pieces version: Pieces for Developers 2.0.1
Platform Linux Linux 6.1.29-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed May 17 14:00:55 UTC 2023

Hello, I am having this issue since today (May 19th 2023).

I usually open Android Studio, and when I open a project I see the Pieces OS window popup, start, and then close.
After that, the Android Studio (IntelliJ) plugin is connected and I see my pieces on the "Pieces" tab.

But today I started seeing this error message from Android Studio: "Failed to connect to Pieces OS" "Please make sure Pieces OS is running and up-to-date"

When I click the refresh button on the pieces list I see: "Failed to refresh saved snippets" "Please make sure Pieces OS is running and up-to-date"

I have the Pieces for Developers app open and I see that Pieces OS is running and I can use it normally (create new snippet, edit saved snippet...).

It's not always the same though... I have closed and reopened the project, I see the "Failed to connect to Pieces OS" error, but now I CAN see my snippets in the Pieces tab, but if I click the refresh button there, I still see the "Failed to refresh saved snippets" error, all while the Pieces for developers app is connected and running fine. Here's a screenshot I took after doind that:

![2023-05-19_08-22](https://github.com/pieces-app/documentation/assets/7395872/bc70fdee-a9c2-48f2-827f-0c0707222226)

Let me know if I can provide more information to debug this issue. 

Thanks!

**Comment by jordan-pieces** [comment]
Hey @mdev88 - this is an interesting issue, you may just need to update the plugin inside of android studio, and following the update to the plugin, you may have to restart Android Studio in order to see this update take effect. 

Second to that, I would try uninstalling the Pieces plugin from android studio, and then installing the plugin fresh to see if that resolves it as well. (Note that you wont loose your code snippets that you have saved since it is stored in Pieces OS)

I can follow up with you more if neither of those solutions work, and also we have a discord server where we can get a ticket open for you so others can assist. Since you are on linux we would love to get feedback on the experience and also other improvements that can be made! 

Heres the link: https://discord.gg/getpieces

If you want to continue our conversation here, let me know.

**Comment by mdev88** [comment]
Hey @jordan-pieces , thank you for your quick reply!

I checked if there were any updates of the Android Studio plugin and there were not. So I uninstelled it, and reinstalled it. Restarted Android Studio... and got the same error as before. This time, I can't even see the snippets in the Pieces tab.

Also, I forgot I also have another error I should report on another issue, but since we are at it, here it goes. Every time I open a project, I also see this other error (the one in red):

![image](https://github.com/pieces-app/documentation/assets/7395872/0d97a74d-7f0e-40fa-a3f1-065f835a0a4f)

If I click that I get a stacktrace:

![image](https://github.com/pieces-app/documentation/assets/7395872/a8ec58d3-72da-431b-9029-b92e8790e111)

Here is the full stacktrace:

```
java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:252)
	at com.intellij.ui.jcef.JBCefBrowserBase.lambda$new$3(JBCefBrowserBase.java:152)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:127)
	at com.intellij.ui.jcef.JBCefBrowserBase.<init>(JBCefBrowserBase.java:152)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:190)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:150)
	**at app.pieces.plugins.jetbrains.ui.views.onboarding.OnboardingWindow.<init>(OnboardingWindow.kt:21)
	at app.pieces.plugins.jetbrains.ui.views.onboarding.WindowFactory.createToolWindowContent(WindowFactory.kt:11)**
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:529)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:508)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:921)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:861)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:850)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindow(ToolWindowManagerImpl.kt:749)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.show(ToolWindowImpl.kt:264)
	at com.intellij.openapi.wm.ToolWindow.show(ToolWindow.java:65)
	**at app.pieces.plugins.jetbrains.listeners.OnboardingStartupActivity.runActivity(OnboardingStartupActivity.kt:16)**
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:311)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:290)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:285)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$2.run(StartupManagerImpl.kt:249)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:398)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:390)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

I see the pieces plugin mentioned there, and this only happens when the Pieces plugin is enabled, so... 
I didn't report this error because everything worked just fine before, but maybe it has something to do with the new error.
Let me know if you want me to create a separate issue to track that other error.

Thanks!

**Comment by mdev88** [comment]
Ahh, I see where's the problem:

![image](https://github.com/pieces-app/documentation/assets/7395872/ae6114c8-907d-425c-be5a-bb4616172a00)


That's when I try to install the Zip file you attached in your previous message. 

Hope that helps!

Let me know if I can try something else.

Thanks!

**Comment by kuba-pieces** [comment]
That doesn't look right. [Android Studio Release list](https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html#2022) shows that the latest stable is Flamingo (based on 222 IDEA builds). Also, the main page for Android Studio project shows Flamingo as default download option.

**Comment by mdev88** [comment]
I have installed Android Studio from the AUR. Maybe that package is not updated immediately...
I'll try to download the bundle from the Android Studio page directly and try again and let you know.

Thanks!

**Comment by mdev88** [comment]
@jordan-pieces thanks! I'm here if you need me tro try anything else. 
I may apply to become a beta tester in the near future also :)

**Comment by jordan-pieces** [comment]
@mdev88 there was a patch build for OS Server that has some changes related to the issues you mentioned about - hopefully they fix the connection error message that you are getting. Have you gotten the newest version of Pieces OS?

**Comment by mdev88** [comment]
Fantastic! It's working now :partying_face: 
I still get the Java error, which I'm not sure how to fix, but it's not a big deal.
You've been super helpful, thanks!

**Comment by mdev88** [comment]
If someone also has the "JCEF is not supported in this env or failed to initialize" error, here is how I fixed it:

- Go to Help -> Find action
- Search and select "Choose Boot Java Runtime for the IDE"
- In that popup, select a JetBrains runtime that has JCEF.

Then restart the IDE and the error is gone.

**Comment by jordan-pieces** [comment]
@mdev88 thanks for sending this over - we will add this to our frequently asked questions and to the discord as well for other users to find. Were you able to join the discord server? all good if not just wanted to make sure it was communicated if you would like to stay in touch in the future :)

**Comment by jordan-pieces** [comment]
I will close this later today once i ensure and link the new pages to this location!
